source:         ./
destination:    ./_site
exclude:        [".editorconfig", ".gitignore", "bower.json","LICENSE.md","package.json", "node_modules", "README.md", "bower_components"]
baseurl: 		/Activate
